"use client";

import { useEffect, useState } from "react";
import { 
  X, 
  Target, 
  BrainCircuit, 
  TrendingUp, 
  AlertCircle,
  Lightbulb
} from "lucide-react";

interface ExplainData {
  score: number;
  why: string[];
  next_actions: string[];
}

export function ExplainSidebar({ 
  dealId, 
  dealName, 
  onClose 
}: { 
  dealId: string; 
  dealName: string;
  onClose: () => void;
}) {
  const [data, setData] = useState<ExplainData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchExplain() {
      try {
        const res = await fetch(`/api/deals/${dealId}/explain`);
        if (res.ok) {
          setData(await res.json());
        }
      } catch (err) {
        console.error("Failed to fetch explanation:", err);
      } finally {
        setLoading(false);
      }
    }
    fetchExplain();
  }, [dealId]);

  return (
    <div className="fixed inset-y-0 right-0 w-80 bg-white shadow-2xl z-50 transform transition-transform border-l border-slate-100 flex flex-col">
      <div className="p-4 border-b flex items-center justify-between bg-slate-50/50">
        <div className="flex items-center gap-2">
          <BrainCircuit className="w-5 h-5 text-indigo-600" />
          <h2 className="font-semibold text-slate-800">AI Breakdown</h2>
        </div>
        <button onClick={onClose} className="p-1 hover:bg-slate-200 rounded-lg transition-colors">
          <X className="w-5 h-5 text-slate-500" />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-6">
        <div>
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Deal</h3>
          <p className="text-slate-800 font-medium truncate">{dealName}</p>
        </div>

        {loading ? (
          <div className="space-y-4 animate-pulse">
            <div className="h-20 bg-slate-50 rounded-xl" />
            <div className="h-40 bg-slate-50 rounded-xl" />
            <div className="h-40 bg-slate-50 rounded-xl" />
          </div>
        ) : data ? (
          <>
            <div className="bg-indigo-50/50 p-4 rounded-xl border border-indigo-100/50 text-center">
              <p className="text-sm font-medium text-indigo-600 mb-1">Win Probability</p>
              <p className="text-3xl font-bold text-indigo-900">{data.score}%</p>
            </div>

            <div className="space-y-3">
              <div className="flex items-center gap-2 text-slate-800 font-semibold mb-3">
                <Target className="w-4 h-4 text-slate-400" />
                <h4>Why this score?</h4>
              </div>
              <ul className="space-y-3">
                {data.why.map((reason, i) => (
                  <li key={i} className="flex gap-3 text-sm text-slate-600 leading-relaxed">
                    <span className="shrink-0">{reason.startsWith('✅') ? '✅' : '⚠️'}</span>
                    <span>{reason.replace(/[✅⚠️]/g, '').trim()}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="space-y-3 pt-4 border-t border-slate-100">
              <div className="flex items-center gap-2 text-slate-800 font-semibold mb-3">
                <Lightbulb className="w-4 h-4 text-amber-500 fill-amber-500/10" />
                <h4>Next Best Actions</h4>
              </div>
              <div className="space-y-2">
                {data.next_actions.map((action, i) => (
                  <div key={i} className="bg-slate-50 border border-slate-100 p-3 rounded-lg text-sm text-indigo-700 font-medium flex items-start gap-2">
                    <TrendingUp className="w-3.5 h-3.5 mt-0.5 shrink-0 opacity-50" />
                    {action}
                  </div>
                ))}
              </div>
            </div>
          </>
        ) : (
          <div className="text-center py-10 space-y-2">
            <AlertCircle className="w-8 h-8 text-slate-300 mx-auto" />
            <p className="text-slate-500 text-sm">Could not load AI analysis.</p>
          </div>
        )}
      </div>

      <div className="p-4 bg-slate-50 border-t border-slate-100 italic text-[10px] text-slate-400 leading-tight">
        Analysis generated by DealGPT ML Engine. Factors are calculated based on historical conversion patterns.
      </div>
    </div>
  );
}
